FROM golang:1.20-alpine3.18 AS build
# Support CGO and SSL
RUN apk --no-cache add gcc g++ make
RUN apk add git
WORKDIR /go/src/app

COPY ./basketball ./

RUN go get -d -v ./...
RUN go install -v ./...

EXPOSE 8080
# Install server application
CMD ["go", "run", "main.go", "--network='host'"]

##RUN go get github.com/astaxie/beego
##RUN go get github.com/beego/bee
##RUN go install github.com/beego/bee
#
##RUN go get github.com/gorilla/mux
#RUN GOOS=linux go build -ldflags="-s -w" -o ./bin/test ./main.go
#
#FROM alpine:3.10
#RUN apk --no-cache add ca-certificates
#WORKDIR /usr/bin
#COPY --from=build /go/src/app/bin /go/bin
#EXPOSE 8080
#ENTRYPOINT /go/bin/test --port 8080