version: "3"
services:
  backend-go:
    container_name: backend_app_go
    build:
        dockerfile: Dockerfile_back
        context: .
    ports:
      - "8080:8080"
    volumes:
      - ./basketball:/go/src/app
  frontend-r:
    container_name: frontend_app_r
    build:
      dockerfile: Dockerfile_front
      context: .
    ports:
      - "3000:3000"
  nginx-r:
    depends_on:
      - frontend-r
      - backend-go
    build:
      dockerfile: Dockerfile_nginx
      context: .
    ports:
      - "80:80"
  mysql-m:
    build:
      dockerfile: Dockerfile_mysql
      context: .
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db__name:/var/lib/mysql
volumes:
  db__name:
