FROM node:lts as build
# Set the working directory to /App inside the container
WORKDIR /app
# Copy App files
COPY ./Basketball-front/package.json ./
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install
COPY ./Basketball-front .
# Build the App
RUN npm run build


# Bundle static assets with nginx
FROM nginx:1.21.0-alpine as nginx-front
ENV NODE_ENV nginx-front
COPY --from=build /app/public /var/www/html/public/
COPY configs/front/nginx.conf /etc/nginx/conf.d/default.conf
# Copy built assets from `builder` image
# Add your apache.conf
# Expose port
# Start nginx
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 3000
#EXPOSE 3000
